implement toast messages for network error feedback
FireTracker-App/firetracker-android pull request #8
Opened 2020-11-07 23:01 UTC by techchrism

2020-11-08 05:36 UTC, coderbot16 approved these changes
lgtm

2020-11-08 05:37 UTC, coderbot16 requested changes
spaces are bad

2020-11-09 20:09 UTC, 4096x2160 reviewed
Looks good

2020-11-09 20:09 UTC, 4096x2160 approved these changes

2020-11-09 20:09 UTC, merged